import { http } from './http'

export const adminApi = {
  dashboard: () => http.get('/api/admin/dashboard'),
  performances: () => http.get('/api/admin/performances'),
  performance: (id) => http.get(`/api/admin/performances/${id}`),
  createPerformance: (payload) => http.post('/api/admin/performances', payload),
  updatePerformance: (id, payload) => http.put(`/api/admin/performances/${id}`, payload),
  deletePerformance: (id) => http.delete(`/api/admin/performances/${id}`),
  publishPerformance: (id) => http.put(`/api/admin/performances/${id}/publish`),
  offlinePerformance: (id) => http.put(`/api/admin/performances/${id}/offline`),
  movies: () => http.get('/api/admin/movies'),
  movie: (id) => http.get(`/api/admin/movies/${id}`),
  createMovie: (payload) => http.post('/api/admin/movies', payload),
  updateMovie: (id, payload) => http.put(`/api/admin/movies/${id}`, payload),
  deleteMovie: (id) => http.delete(`/api/admin/movies/${id}`),
  homepageRecommendations: () => http.get('/api/admin/homepage-recommendations'),
  saveHomepageRecommendation: (sectionCode, items) => http.put(`/api/admin/homepage-recommendations/${sectionCode}`, { items }),
  cinemas: () => http.get('/api/admin/cinemas'),
  createCinema: (payload) => http.post('/api/admin/cinemas', payload),
  updateCinema: (id, payload) => http.put(`/api/admin/cinemas/${id}`, payload),
  deleteCinema: (id) => http.delete(`/api/admin/cinemas/${id}`),
  cinemaSchedules: (id) => http.get(`/api/admin/cinemas/${id}/schedules`),
  saveCinemaSchedule: (id, payload) => http.post(`/api/admin/cinemas/${id}/schedules`, payload),
  createStaffUser: (payload) => http.post('/api/admin/staff-users', payload),
  detailBlocks: (id) => http.get(`/api/admin/performances/${id}/detail-blocks`),
  createDetailBlock: (id, payload) => http.post(`/api/admin/performances/${id}/detail-blocks`, payload),
  updateDetailBlock: (id, payload) => http.put(`/api/admin/performance-detail-blocks/${id}`, payload),
  deleteDetailBlock: (id) => http.delete(`/api/admin/performance-detail-blocks/${id}`),
  reorderDetailBlocks: (id, ids) => http.put(`/api/admin/performances/${id}/detail-blocks/reorder`, { ids }),
  uploadImage: (file) => {
    const formData = new FormData()
    formData.append('file', file)
    return http.post('/api/admin/upload/image', formData, { timeout: 120000 })
  },
  uploadLocalImage: (path) => http.post('/api/admin/upload/local-image', { path }),
  venues: () => http.get('/api/admin/venues'),
  createVenue: (payload) => http.post('/api/admin/venues', payload),
  updateVenue: (id, payload) => http.put(`/api/admin/venues/${id}`, payload),
  disableVenue: (id) => http.put(`/api/admin/venues/${id}/disable`),
  deleteVenue: (id) => http.delete(`/api/admin/venues/${id}`),
  areas: (venueId) => http.get(`/api/admin/venues/${venueId}/areas`),
  createArea: (venueId, payload) => http.post(`/api/admin/venues/${venueId}/areas`, payload),
  updateArea: (id, payload) => http.put(`/api/admin/venue-areas/${id}`, payload),
  seats: (venueId) => http.get(`/api/admin/venues/${venueId}/seats`),
  generateSeats: (venueId, payload) => http.post(`/api/admin/venues/${venueId}/seats/generate`, payload),
  clearSeats: (venueId) => http.delete(`/api/admin/venues/${venueId}/seats`),
  updateSeat: (id, payload) => http.put(`/api/admin/seats/${id}`, payload),
  sessions: () => http.get('/api/admin/sessions'),
  createSession: (payload) => http.post('/api/admin/sessions', payload),
  updateSession: (id, payload) => http.put(`/api/admin/sessions/${id}`, payload),
  deleteSession: (id) => http.delete(`/api/admin/sessions/${id}`),
  initSessionSeats: (sessionId) => http.post(`/api/admin/sessions/${sessionId}/init-seats`),
  sessionSeats: (sessionId) => http.get(`/api/admin/sessions/${sessionId}/seats`),
  ticketLevels: (sessionId) => http.get(`/api/admin/sessions/${sessionId}/ticket-levels`),
  createTicketLevel: (payload) => http.post('/api/admin/ticket-levels', payload),
  updateTicketLevel: (id, payload) => http.put(`/api/admin/ticket-levels/${id}`, payload),
  deleteTicketLevel: (id) => http.delete(`/api/admin/ticket-levels/${id}`),
  saleBatches: () => http.get('/api/admin/sale-batches'),
  createSaleBatch: (payload) => http.post('/api/admin/sale-batches', payload),
  updateSaleBatch: (id, payload) => http.put(`/api/admin/sale-batches/${id}`, payload),
  startBatch: (id) => http.post(`/api/admin/sale-batches/${id}/start`),
  lockBatch: (id) => http.post(`/api/admin/sale-batches/${id}/lock`),
  initRedisStock: (id) => http.post(`/api/admin/sale-batches/${id}/init-redis-stock`),
  batchSummary: (id) => http.get(`/api/admin/sale-batches/${id}/stock-summary`),
  inventory: (params = {}) => http.get('/api/admin/inventory', { params }),
  stockPool: () => http.get('/api/admin/stock-pool'),
  sessionStockPool: (sessionId) => http.get(`/api/admin/sessions/${sessionId}/stock-pool`)
}
